services:
  eureka-server:
    build: .
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - eureka-server

networks:
  eureka-server:
    driver: bridge