services:
  eureka-server:
    build: .
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - eureka-server

networks:
  eureka-server:
    driver: bridge